#!/bin/bash

# ---------------------------------------------
# Script: kubctl-0x01
# Objective: Scale a Django app in Kubernetes
# ---------------------------------------------

# CHANGE THIS to the name of your Django deployment
DEPLOYMENT_NAME=django-app

# CHANGE THIS if your app uses a different service or port
SERVICE_URL=http://localhost:8000

echo "🔹 Scaling deployment to 3 replicas..."
kubectl scale deployment $DEPLOYMENT_NAME --replicas=3

echo ""
echo "🔹 Waiting for pods to start..."
sleep 5

echo ""
echo "🔹 Verifying running pods..."
kubectl get pods

echo ""
echo "🔹 Running load test with wrk (10 seconds)..."
echo "   Make sure your service is accessible at $SERVICE_URL"
wrk -t2 -c20 -d10s $SERVICE_URL

echo ""
echo "🔹 Monitoring resource usage (CPU & Memory)..."
kubectl top pods
